name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  e2e-tests:
    needs: unit-tests
    uses: ./.github/workflows/e2e-tests.yml

  deploy:
    needs: e2e-tests
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-to-gh-pages.yml
