name: Tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 24 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node-version }}
          cache: true
      - name: Run linting
        run: pnpm run lint
      - name: Run unit + integration tests
        run: pnpm test
      - name: Build
        run: pnpm run build
